package util;

public class Enums {
    public enum Difficulty{
        THEORETICAL_VERY_EASY, THEORETICAL_EASY, THEORETICAL_MEDIUM, THEORETICAL_HARD, THEORETICAL_VERY_HARD,
        PROGRAMMING_VERY_EASY, PROGRAMMING_EASY, PROGRAMMING_MEDIUM, PROGRAMMING_HARD, PROGRAMMING_VERY_HARD
    }
}
